"""
planner.py — Study Plan + Calendar Export
=========================================
Turns a skill gap (missing skills + estimated hours) into a concrete
week-by-week study plan, and exports it as a downloadable .ics calendar the
student can import into Google/Outlook/Apple Calendar.

Pure, dependency-free, testable Python — no AI, easy to defend in a viva.

    weeks = build_weekly_plan(per_skill, hours_per_week=10)
    ics   = plan_to_ics(weeks, title="SkillBridge study plan")
    md    = plan_to_markdown(weeks)
"""

import datetime
import hashlib


def build_weekly_plan(per_skill, hours_per_week: int = 10, start_date=None):
    """
    Pack skills into consecutive weeks up to a weekly study budget.

    per_skill : list of (skill, hours) — e.g. analyzer.estimate_timeline()['per_skill'].
    Returns   : list of week dicts:
        {"week": 1, "start": date, "end": date, "items": [(skill, hours), ...], "hours": total}
    A skill larger than the weekly budget is split across consecutive weeks.
    """
    hours_per_week = max(1, int(hours_per_week))
    start_date = start_date or datetime.date.today()
    # move start to the next Monday so weeks line up nicely on a calendar
    start_date = start_date + datetime.timedelta(days=(7 - start_date.weekday()) % 7)

    weeks = []
    cur_items, cur_hours, week_no = [], 0, 1

    def _flush():
        nonlocal cur_items, cur_hours, week_no
        if not cur_items:
            return
        wk_start = start_date + datetime.timedelta(weeks=week_no - 1)
        weeks.append({
            "week": week_no,
            "start": wk_start,
            "end": wk_start + datetime.timedelta(days=6),
            "items": cur_items,
            "hours": cur_hours,
        })
        cur_items, cur_hours, week_no = [], 0, week_no + 1

    for skill, hours in per_skill:
        remaining = max(1, int(round(hours)))
        while remaining > 0:
            free = hours_per_week - cur_hours
            if free <= 0:
                _flush()
                free = hours_per_week
            take = min(remaining, free)
            cur_items.append((skill, take))
            cur_hours += take
            remaining -= take
            if cur_hours >= hours_per_week:
                _flush()
    _flush()
    return weeks


# ------------------------------------------------------------------ markdown
def plan_to_markdown(weeks) -> str:
    """Render the plan as readable markdown for the app."""
    if not weeks:
        return "_Nothing to schedule — you already cover this role._"
    lines = []
    for w in weeks:
        span = f"{w['start'].strftime('%d %b')} – {w['end'].strftime('%d %b')}"
        skills = ", ".join(f"{s} ({h}h)" for s, h in w["items"])
        lines.append(f"**Week {w['week']}** ({span}) · ~{w['hours']}h — {skills}")
    return "\n\n".join(lines)


# ------------------------------------------------------------------ .ics export
def _esc(text: str) -> str:
    """Escape a value for an iCalendar TEXT field."""
    return (str(text).replace("\\", "\\\\").replace(";", "\\;")
            .replace(",", "\\,").replace("\n", "\\n"))


def _fold(line: str) -> str:
    """Fold long lines to 75 octets per RFC 5545 (continuation lines start with a space)."""
    out, s = [], line
    while len(s) > 75:
        out.append(s[:75])
        s = " " + s[75:]
    out.append(s)
    return "\r\n".join(out)


def plan_to_ics(weeks, title: str = "SkillBridge study plan") -> str:
    """Build an RFC-5545 .ics calendar: one all-day-week event per plan week."""
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    rows = ["BEGIN:VCALENDAR", "VERSION:2.0",
            "PRODID:-//SkillBridge//Study Plan//EN", "CALSCALE:GREGORIAN",
            "METHOD:PUBLISH"]
    for w in weeks:
        skills = ", ".join(f"{s} ({h}h)" for s, h in w["items"])
        uid_seed = f"{w['week']}-{w['start']}-{skills}"
        uid = hashlib.sha1(uid_seed.encode("utf-8")).hexdigest()[:16] + "@skillbridge"
        dtstart = w["start"].strftime("%Y%m%d")
        dtend = (w["end"] + datetime.timedelta(days=1)).strftime("%Y%m%d")  # DTEND is exclusive
        rows += [
            "BEGIN:VEVENT",
            f"UID:{uid}",
            f"DTSTAMP:{now}",
            f"DTSTART;VALUE=DATE:{dtstart}",
            f"DTEND;VALUE=DATE:{dtend}",
            _fold("SUMMARY:" + _esc(f"{title}: Week {w['week']} — learn {skills}")),
            _fold("DESCRIPTION:" + _esc(
                f"Study plan week {w['week']} (~{w['hours']}h). Focus: {skills}. "
                "Generated by SkillBridge.")),
            "END:VEVENT",
        ]
    rows.append("END:VCALENDAR")
    return "\r\n".join(rows) + "\r\n"
